name: Active_vision

task_type: "active_vision"
controller_type: "active_vision"

sub_task_type: "pick"
sub_controller_type: "pick"

mode: "collect"

usd_path: "assets/chemistry_lab/lab_001/lab_001.usd"


max_episodes: 10

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

task:
  max_steps: 800
  obj_paths:
    - path: "/World/conical_bottle02"
      position_range:
        x: [0.15, 0.25]
        y: [-0.35, -0.45]
        z: [0.8, 0.8]
    
    - path: "/World/DryingBox_01" # beaker1
      position_range:
        x: [0.25, 0.25]
        y: [0.1, 0.1]
        z: [0.80, 0.80]

cameras:
  # - prim_path: "/World/Camera1"
  #   name: "ext_camera_1"
  #   translation: [2, 0, 2]
  #   resolution: [256, 256]
  #   focal_length: 6
  #   orientation: [0.61237, 0.35355, 0.35355, 0.61237]
  #   image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "ext_camera_2"
    translation: [0.1, 0.25, 5.3]
    resolution: [256, 256]
    focal_length: 6
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "op_camera"
    resolution: [256, 256]
    image_type: "rgb"
  
  # - prim_path: "/World/Ridgebase/base_link/Camera"
  #   name: "obs_front_camera"
  #   resolution: [256, 256]
  #   image_type: "rgb"

  - prim_path: "/World/Ridgebase/panda_hand/Camera"
    name: "obs_wrist_camera"
    resolution: [256, 256]
    clipping_range: [0, 10.0]
    image_type: "rgb"
  
  # - prim_path: "/World/Ridgebase/base_link/Camera_01"
  #   name: "obs_top_camera"
  #   resolution: [256, 256]
  #   image_type: "rgb"

robot:
  - prim_path: "/World/Franka"
    name: "franka"
    type: "franka"
    position: [-0.4, -0, 0.71]

  - prim_path: "/World/Ridgebase"
    name: "ridgebase"
    type: "ridgebase"
    position: [-0.4, -2, 0.8]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}